# Generated by Django 5.0.2 on 2024-02-20 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fax', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('no_of_employee', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('education_level', models.CharField(max_length=100)),
                ('working_field', models.CharField(max_length=255)),
                ('current_position', models.CharField(max_length=255)),
                ('year_at_company', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('domain', models.CharField(choices=[('program', 'Program'), ('project', 'Project'), ('portfolio', 'Portfolio'), ('oe', 'OE')], max_length=20)),
                ('stage', models.CharField(choices=[('standardize', 'Standardize'), ('measure', 'Measure'), ('control', 'Control'), ('improve', 'Improve'), ('human-resources', 'Human Resources'), ('cultural', 'Cultural'), ('technological', 'Technological'), ('structural', 'Structural')], max_length=20)),
                ('process_group', models.CharField(blank=True, choices=[('initiating', 'Initiating'), ('planning', 'Planning'), ('executing', 'Executing'), ('m&c', 'M & C'), ('closing', 'Closing')], max_length=20, null=True)),
                ('knowledge_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.knowledgearea')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, choices=[('program', 'Program'), ('project', 'Project'), ('portfolio', 'Portfolio'), ('oe', 'OE')], max_length=20, null=True)),
                ('stage', models.CharField(blank=True, choices=[('standardize', 'Standardize'), ('measure', 'Measure'), ('control', 'Control'), ('improve', 'Improve'), ('human-resources', 'Human Resources'), ('cultural', 'Cultural'), ('technological', 'Technological'), ('structural', 'Structural')], max_length=20, null=True)),
                ('result', models.IntegerField()),
                ('total_number', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.employee')),
                ('knowledge_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.knowledgearea')),
            ],
        ),
    ]
