# Generated by Django 5.0.2 on 2024-02-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='process_group',
            field=models.CharField(blank=True, choices=[('Initiating', 'Initiating'), ('Planning', 'Planning'), ('Executing', 'Executing'), ('M&C', 'M&C'), ('Closing', 'Closing')], max_length=20, null=True),
        ),
    ]
